utils::globalVariables(c("..w_names"))
################################################################################

#' Get Dzw component of efficient influence function from nuisance parameters
#'
#' @param g_output Object containing results from fitting the propensity score
#'  regression, as produced by a call to \code{fit_g_mech}.
#' @param m_output Object containing results from fitting the outcome
#'  regression, as produced by a call to \code{fit_m_mech}.
#'
#' @keywords internal
#
compute_Dzw <- function(g_output, m_output) {
  # get g components from output for that nuisance parameter
  g_shifted_A1 <- g_output$g_est$g_pred_shifted_A1
  g_shifted_A0 <- g_output$g_est$g_pred_shifted_A0

  # get m components from output for that nuisance parameter
  m_pred_A1 <- m_output$m_pred$m_pred_A1
  m_pred_A0 <- m_output$m_pred$m_pred_A0

  # compute component Dzw from nuisance parameters
  Dzw_A1 <- g_shifted_A1 * m_pred_A1
  Dzw_A0 <- g_shifted_A0 * m_pred_A0

  # output as simple list
  return(list(
    dzw_cntrl = Dzw_A0,
    dzw_treat = Dzw_A1
  ))
}

################################################################################

#' Get inverse probability weighted (IPW) estimate from nuisance parameters
#'
#' @param g_output Object containing results from fitting the propensity score
#'  regression, as produced by a call to \code{fit_g_mech}.
#' @param e_output Object containing results from fitting the propensity score
#'  regression while conditioning on mediators, as produced by a call to
#'  \code{fit_e_mech}.
#' @param idx_treat A \code{numeric} vector providing the indices corresponding
#'  to units that received treatment (A = 1), for a binary intervention.
#' @param idx_cntrl A \code{numeric} vector providing the indices corresponding
#'  to units that did not receive treatment (A = 0), for a binary intervention.
#'
#' @keywords internal
#
compute_ipw <- function(g_output, e_output, idx_treat, idx_cntrl) {
  # compute components for A = 0 based on symmetry with A = 1 case
  g_shifted_A1 <- g_output$g_est$g_pred_shifted_A1
  g_shifted_A0 <- g_output$g_est$g_pred_shifted_A0
  e_pred_A1 <- e_output$e_est$e_pred_A1
  e_pred_A0 <- e_output$e_est$e_pred_A0

  # subset computed components based on observed treatment status for g
  g_shifted_obs <- rep(NA, length(idx_treat) + length(idx_cntrl))
  g_shifted_A1_obs <- g_shifted_A1[idx_treat]
  g_shifted_A0_obs <- g_shifted_A0[idx_cntrl]
  g_shifted_obs[idx_treat] <- g_shifted_A1_obs
  g_shifted_obs[idx_cntrl] <- g_shifted_A0_obs

  # subset computed components based on observed treatment status for e
  e_pred_obs <- rep(NA, length(idx_treat) + length(idx_cntrl))
  e_pred_A1_obs <- e_pred_A1[idx_treat]
  e_pred_A0_obs <- e_pred_A0[idx_cntrl]
  e_pred_obs[idx_treat] <- e_pred_A1_obs
  e_pred_obs[idx_cntrl] <- e_pred_A0_obs

  # stabilize weights in A-IPW by dividing by sample average since E[g/e] = 1
  mean_aipw <- mean(g_shifted_obs / e_pred_obs)

  # output as simple list
  return(list(
    g_shifted = g_shifted_obs,
    e_pred = e_pred_obs,
    mean_aipw = mean_aipw
  ))
}

################################################################################

#' Cross-validated evaluation of EIF components
#'
#' @param fold Object specifying cross-validation folds as generated by a call
#'  to \code{origami::make_folds}.
#' @param data A \code{data.table} containing the observed data, with columns
#'  in the order specified by the NPSEM (Y, Z, A, W), with column names set
#'  appropriately based on the original input data. Such a structure is merely
#'  a convenience utility to passing data around to the various core estimation
#'  routines and is automatically generated as part of a call to the user-facing
#'  wrapper function \code{medshift}.
#' @param delta A \code{numeric} value indicating the degree of shift in the
#'  intervention to be used in defining the causal quantity of interest. In the
#'  case of binary interventions, this takes the form of an incremental
#'  propensity score shift, acting as a multiplier of the probability with which
#'  a given observational unit receives the intervention (EH Kennedy, 2018,
#'  JASA; <doi:10.1080/01621459.2017.1422737>).
#' @param lrnr_stack_g A \code{Stack} object, or other learner class (inheriting
#'  from \code{Lrnr_base}), containing a single or set of instantiated learners
#'  from the \code{sl3} package, to be used in fitting a model for the
#'  propensity score, i.e., g = P(A | W).
#' @param lrnr_stack_e A \code{Stack} object, or other learner class (inheriting
#'  from \code{Lrnr_base}), containing a single or set of instantiated learners
#'  from the \code{sl3} package, to be used in fitting a cleverly parameterized
#'  propensity score that includes the mediators, i.e., e = P(A | Z, W).
#' @param lrnr_stack_m A \code{Stack} object, or other learner class (inheriting
#'  from \code{Lrnr_base}), containing a single or set of instantiated learners
#'  from the \code{sl3} package, to be used in fitting the outcome regression,
#'  i.e., m(A, Z, W).
#' @param lrnr_stack_phi A \code{Stack} object, or other learner class
#'  (inheriting from \code{Lrnr_base}), containing a single or set of
#'  instantiated learners from the \code{sl3} package, to be used in fitting a
#'  reduced regression useful for computing the efficient one-step estimator,
#'  i.e., phi(W) = E[m(A = 1, Z, W) - m(A = 0, Z, W) | W).
#' @param w_names A \code{character} vector of the names of the columns that
#'  correspond to baseline covariates (W). The input for this argument is
#'  automatically generated by a call to the wrapper function \code{medshift}.
#' @param z_names A \code{character} vector of the names of the columns that
#'  correspond to mediators (Z). The input for this argument is automatically
#'  generated by a call to the wrapper function \code{medshift}.
#'
#' @importFrom data.table data.table
#' @importFrom origami training validation fold_index
#'
#' @keywords internal
#
cv_eif <- function(fold,
                   data,
                   delta,
                   lrnr_stack_g,
                   lrnr_stack_e,
                   lrnr_stack_m,
                   lrnr_stack_phi,
                   w_names,
                   z_names) {
  # make training and validation data
  train_data <- origami::training(data)
  valid_data <- origami::validation(data)

  # compute nuisance parameters eta = (g, m, e, phi)
  ## 1) fit regression for incremental propensity score intervention
  g_out <- fit_g_mech(
    data = train_data, valid_data = valid_data,
    delta = delta,
    lrnr_stack = lrnr_stack_g, w_names = w_names
  )

  ## 2) fit clever regression for treatment, conditional on mediators
  e_out <- fit_e_mech(
    data = train_data, valid_data = valid_data,
    lrnr_stack = lrnr_stack_e,
    z_names = z_names, w_names = w_names
  )

  ## 3) fit regression for incremental propensity score intervention
  m_out <- fit_m_mech(
    data = train_data, valid_data = valid_data,
    lrnr_stack = lrnr_stack_m,
    z_names = z_names, w_names = w_names
  )

  ## 4) difference-reduced dimension regression for phi
  phi_est <- fit_phi_mech(
    data = valid_data, lrnr_stack = lrnr_stack_phi,
    m_output = m_out, w_names = w_names
  )


  # get indices of treated and control units in validation data
  idx_A1 <- which(valid_data$A == 1)
  idx_A0 <- which(valid_data$A == 0)


  # compute component Dzw from nuisance parameters
  Dzw_groupwise <- compute_Dzw(g_output = g_out, m_output = m_out)
  Dzw <- Dzw_groupwise$dzw_cntrl + Dzw_groupwise$dzw_treat


  # compute component Da from nuisance parameters
  g_pred_A1 <- g_out$g_est$g_pred_A1
  g_pred_A0 <- g_out$g_est$g_pred_A0
  g_pred_obs <- g_out$g_est$g_pred_natural
  Da_numerator <- delta * phi_est * (valid_data$A - g_pred_A1)
  Da_denominator <- (delta * g_pred_A1 + g_pred_A0)^2
  Da <- Da_numerator / Da_denominator


  # compute component Dy from nuisance parameters
  ipw_groupwise <- compute_ipw(
    g_output = g_out, e_output = e_out,
    idx_treat = idx_A1, idx_cntrl = idx_A0
  )
  m_pred_obs <- rep(NA, nrow(valid_data))
  m_pred_A1_obs <- m_out$m_pred$m_pred_A1[idx_A1]
  m_pred_A0_obs <- m_out$m_pred$m_pred_A0[idx_A0]
  m_pred_obs[idx_A1] <- m_pred_A1_obs
  m_pred_obs[idx_A0] <- m_pred_A0_obs
  # stabilize weights in AIPW by dividing by sample average since E[g/e] = 1
  mean_aipw <- ipw_groupwise$mean_aipw
  g_shifted <- ipw_groupwise$g_shifted
  e_pred <- ipw_groupwise$e_pred
  Dy <- ((g_shifted / e_pred) / mean_aipw) * (valid_data$Y - m_pred_obs)


  # output list
  out <- list(data.table::data.table(
    Dy = Dy, Da = Da, Dzw = Dzw,
    fold = origami::fold_index()
  ))
  return(out)
}
