#' Substitution estimator
#'
#' @param data A \code{data.table} containing the observed data, with columns
#'  in the order specified by the NPSEM (Y, Z, A, W), with column names set
#'  appropriately based on the original input data. Such a structure is merely
#'  a convenience utility to passing data around to the various core estimation
#'  routines and is automatically generated as part of a call to the user-facing
#'  wrapper function \code{medshift}.
#' @param delta A \code{numeric} value indicating the degree of shift in the
#'  intervention to be used in defining the causal quantity of interest. In the
#'  case of binary interventions, this takes the form of an incremental
#'  propensity score shift, acting as a multiplier of the probability with which
#'  a given observational unit receives the intervention (EH Kennedy, 2018,
#'  JASA; <doi:10.1080/01621459.2017.1422737>).
#' @param g_lrnrs A \code{Stack} object, or other learner class (inheriting from
#'  \code{Lrnr_base}), containing a single or set of instantiated learners from
#'  the \code{sl3} package, to be used in fitting a model for the propensity
#'  score, i.e., g = P(A | W).
#' @param m_lrnrs A \code{Stack} object, or other learner class (inheriting
#'  from \code{Lrnr_base}), containing a single or set of instantiated learners
#'  from the \code{sl3} package, to be used in fitting the outcome regression,
#'  i.e., m(A, Z, W).
#' @param w_names A \code{character} vector of the names of the columns that
#'  correspond to baseline covariates (W). The input for this argument is
#'  automatically generated by a call to the wrapper function \code{medshift}.
#' @param z_names A \code{character} vector of the names of the columns that
#'  correspond to mediators (Z). The input for this argument is automatically
#'  generated by a call to the wrapper function \code{medshift}.
#' @param shift_type A choice of the type of stochastic treatment regime to use
#'  -- either \code{"mtp"} for a modified treatment policy that shifts the
#'  center of the observed intervention distribution by the scalar \code{delta}
#'  or \code{"ipsi"} for an incremental propensity score shift that multiples
#'  the odds of receiving the intervention by the scalar \code{delta}.
#' @param ... Other arguments currently ignored.
#
est_substitution <- function(data,
                             delta,
                             g_lrnrs,
                             m_lrnrs,
                             w_names,
                             z_names,
                             shift_type = c("ipsi", "mtp"),
                             ...) {
  # estimate propensity score
  g_out <- fit_g_mech(
    data = data, delta = delta,
    lrnr_stack = g_lrnrs, w_names = w_names, shift_type = shift_type
  )

  # fit regression for incremental propensity score intervention
  m_out <- fit_m_mech(
    data = data, lrnr_stack = m_lrnrs,
    z_names = z_names, w_names = w_names, shift_type = shift_type
  )

  # compute Dzw component of EIF using convenience function
  Dzw_est <- compute_Dzw(g_output = g_out, m_output = m_out,
                         shift_type = shift_type)

  if (shift_type == "ipsi") {
    # compute estimator
    estim_sub <- mean(Dzw_est$dzw_cntrl) + mean(Dzw_est$dzw_treat)
  } else if (shift_type == "mtp") {
    # compute estimator
    estim_sub <- as.numeric(Dzw_est$dzw)
  }

  # output
  estim_sub_out <- list(theta = estim_sub, type = "sub")
  return(estim_sub_out)
}
