utils::globalVariables(c("..w_names"))

#' Fit intervention-specific nuisance parameter
#'
#' @param data A \code{data.table} containing the observed data, with columns
#'  in the order specified by the NPSEM (Y, Z, A, W), with column names set
#'  appropriately based on the original input data. Such a structure is merely
#'  a convenience utility to passing data around to the various core estimation
#'  routines and is automatically generated as part of a call to the user-facing
#'  wrapper function \code{medshift}.
#' @param lrnr_stack A \code{Stack} object, or other learner class (inheriting
#'  from \code{Lrnr_base}), containing a single or set of instantiated learners
#'  from the \code{sl3} package, to be used in fitting a cleverly parameterized
#'  propensity score that includes the mediators, i.e., e = P(A | Z, W).
#' @param m_output ...
#' @param w_names A \code{character} vector of the names of the columns that
#'  correspond to baseline covariates (W). The input for this argument is
#'  automatically generated by a call to the wrapper function \code{medshift}.
#'
#' @importFrom data.table data.table as.data.table
#' @importFrom sl3 sl3_Task
#
fit_phi_mech <- function(data, lrnr_stack, m_output, w_names) {
  # difference-reduced dimension regression for phi
  m_pred_A1 <- m_output$m_pred$m_pred_A1
  m_pred_A0 <- m_output$m_pred$m_pred_A0
  m_pred_diff <- m_pred_A1 - m_pred_A0

  # construct data structure for use with task objects
  phi_data <- data.table::data.table(m_diff = m_pred_diff, data[, ..w_names])
  phi_task <- sl3::sl3_Task$new(
    data = phi_data,
    covariates = w_names,
    outcome = "m_diff",
    outcome_type = "continuous"
  )

  # fit stack of learners and predict on the same data set
  phi_fit <- lrnr_stack$train(phi_task)
  phi_est <- phi_fit$predict()
  return(phi_est)
}
