utils::globalVariables(c("A", ".N", "..w_names"))
################################################################################

#' Fit propensity score with incremental stochastic shift intervention
#'
#' @param data A \code{data.table} containing the observed data, with columns
#'  in the order specified by the NPSEM (Y, Z, A, W), with column names set
#'  appropriately based on the original input data. Such a structure is merely
#'  a convenience utility to passing data around to the various core estimation
#'  routines and is automatically generated as part of a call to the user-facing
#'  wrapper function \code{medshift}.
#' @param valid_data A holdout data set, with columns exactly matching those
#'  appearing in the preceding argument \code{data}, to be used for estimation
#'  via cross-fitting. Optional, defaulting to \code{NULL}.
#' @param delta A \code{numeric} value indicating the degree of shift in the
#'  intervention to be used in defining the causal quantity of interest. In the
#'  case of binary interventions, this takes the form of an incremental
#'  propensity score shift, acting as a multiplier of the probability with which
#'  a given observational unit receives the intervention (EH Kennedy, 2018,
#'  JASA; <doi:10.1080/01621459.2017.1422737>).
#' @param lrnr_stack A \code{Stack} object, or other learner class (inheriting
#'  from \code{Lrnr_base}), containing a single or set of instantiated learners
#'  from the \code{sl3} package, to be used in fitting a model for the
#'  propensity score, i.e., g = P(A | W).
#' @param w_names A \code{character} vector of the names of the columns that
#'  correspond to baseline covariates (W). The input for this argument is
#'  automatically generated by a call to the wrapper function \code{medshift}.
#'
#' @importFrom data.table as.data.table copy ":="
#' @importFrom sl3 sl3_Task
#
fit_g_mech <- function(data, valid_data = NULL,
                       delta, lrnr_stack, w_names,
                       type = c()) {
  #  construct task for propensity score fit
  g_task <- sl3::sl3_Task$new(
    data = data,
    covariates = w_names,
    outcome = "A"
  )

  # fit and predict
  g_fit_stack <- lrnr_stack$train(g_task)

  # use full data for counterfactual prediction if no validation data provided
  if (is.null(valid_data)) {
    # copy full data
    data_A1 <- data.table::copy(data)
  } else {
    # copy only validation data
    data_A1 <- data.table::copy(valid_data)
  }

  # set intervention A = 1
  data_A1[, A := rep(1, .N)]
  g_task_A1 <- sl3_Task$new(
    data = data_A1,
    covariates = w_names,
    outcome = "A"
  )
  g_pred_A1 <- g_fit_stack$predict(g_task_A1)

  # compute A = 0 case by symmetry
  g_pred_A0 <- 1 - g_pred_A1

  # directly computed the shifted propensity score
  g_pred_shifted_A1 <- (delta * g_pred_A1) /
    (delta * g_pred_A1 + (1 - g_pred_A1))

  # compute shifted propensity score for A = 0 by symmetry
  g_pred_shifted_A0 <- 1 - g_pred_shifted_A1

  # bounding to numerical precision
  g_pred_A1 <- bound_precision(g_pred_A1)
  g_pred_A0 <- bound_precision(g_pred_A0)
  g_pred_shifted_A1 <- bound_precision(g_pred_shifted_A1)
  g_pred_shifted_A0 <- bound_precision(g_pred_shifted_A0)

  # bounding for potential positivity issues
  g_pred_A1 <- bound_propensity(g_pred_A1)
  g_pred_A0 <- bound_propensity(g_pred_A0)
  g_pred_shifted_A1 <- bound_propensity(g_pred_shifted_A1)
  g_pred_shifted_A0 <- bound_propensity(g_pred_shifted_A0)

  # output
  out <- list(
    g_est = data.table::data.table(cbind(
      g_pred_A1 = g_pred_A1,
      g_pred_A0 = g_pred_A0,
      g_pred_shifted_A1 = g_pred_shifted_A1,
      g_pred_shifted_A0 = g_pred_shifted_A0
    )),
    g_fit = g_fit_stack
  )
  return(out)
}

################################################################################

#' Fit propensity score regression while conditioning on mediators
#'
#' @param data A \code{data.table} containing the observed data, with columns
#'  in the order specified by the NPSEM (Y, Z, A, W), with column names set
#'  appropriately based on the original input data. Such a structure is merely
#'  a convenience utility to passing data around to the various core estimation
#'  routines and is automatically generated as part of a call to the user-facing
#'  wrapper function \code{medshift}.
#' @param valid_data A holdout data set, with columns exactly matching those
#'  appearing in the preceding argument \code{data}, to be used for estimation
#'  via cross-fitting. Optional, defaulting to \code{NULL}.
#' @param lrnr_stack A \code{Stack} object, or other learner class (inheriting
#'  from \code{Lrnr_base}), containing a single or set of instantiated learners
#'  from the \code{sl3} package, to be used in fitting a cleverly parameterized
#'  propensity score that includes the mediators, i.e., e = P(A | Z, W).
#' @param w_names A \code{character} vector of the names of the columns that
#'  correspond to baseline covariates (W). The input for this argument is
#'  automatically generated by a call to the wrapper function \code{medshift}.
#' @param z_names A \code{character} vector of the names of the columns that
#'  correspond to mediators (Z). The input for this argument is automatically
#'  generated by a call to the wrapper function \code{medshift}.
#'
#' @importFrom data.table as.data.table
#' @importFrom sl3 sl3_Task
#
fit_e_mech <- function(data, valid_data = NULL,
                       lrnr_stack, z_names, w_names) {
  # construct task for nuisance parameter fit
  e_task <- sl3::sl3_Task$new(
    data = data,
    covariates = c(z_names, w_names),
    outcome = "A"
  )

  # fit and predict
  e_fit_stack <- lrnr_stack$train(e_task)

  # use full data for counterfactual prediction if no validation data provided
  if (is.null(valid_data)) {
    # copy full data
    data_A1 <- data.table::copy(data)
  } else {
    # copy only validation data
    data_A1 <- data.table::copy(valid_data)
  }

  # set intervention A = 1 in validation data or full data
  data_A1[, A := rep(1, .N)]
  e_task_A1 <- sl3_Task$new(
    data = data_A1,
    covariates = c(z_names, w_names),
    outcome = "A"
  )

  # predict from trained model on counterfactual data
  e_pred_A1 <- e_fit_stack$predict(e_task_A1)

  # get values of nuisance parameter E for A = 0 by symmetry with A = 1 case
  e_pred_A0 <- 1 - e_pred_A1

  # bounding to numerical precision
  e_pred_A1 <- bound_precision(e_pred_A1)
  e_pred_A0 <- bound_precision(e_pred_A0)

  # bounding for potential positivity issues
  e_pred_A1 <- bound_propensity(e_pred_A1)
  e_pred_A0 <- bound_propensity(e_pred_A0)

  # output
  out <- list(
    e_est = data.table::data.table(cbind(
      e_pred_A1 = e_pred_A1,
      e_pred_A0 = e_pred_A0
    )),
    e_fit = e_fit_stack
  )
  return(out)
}

################################################################################

#' Fit outcome regression
#'
#' @param data A \code{data.table} containing the observed data, with columns
#'  in the order specified by the NPSEM (Y, Z, A, W), with column names set
#'  appropriately based on the original input data. Such a structure is merely
#'  a convenience utility to passing data around to the various core estimation
#'  routines and is automatically generated as part of a call to the user-facing
#'  wrapper function \code{medshift}.
#' @param valid_data A holdout data set, with columns exactly matching those
#'  appearing in the preceding argument \code{data}, to be used for estimation
#'  via cross-fitting. Optional, defaulting to \code{NULL}.
#' @param lrnr_stack A \code{Stack} object, or other learner class (inheriting
#'  from \code{Lrnr_base}), containing a single or set of instantiated learners
#'  from the \code{sl3} package, to be used in fitting the outcome regression,
#'  i.e., m(A, Z, W).
#' @param w_names A \code{character} vector of the names of the columns that
#'  correspond to baseline covariates (W). The input for this argument is
#'  automatically generated by a call to the wrapper function \code{medshift}.
#' @param z_names A \code{character} vector of the names of the columns that
#'  correspond to mediators (Z). The input for this argument is automatically
#'  generated by a call to the wrapper function \code{medshift}.
#'
#' @importFrom data.table as.data.table
#' @importFrom sl3 sl3_Task
#
fit_m_mech <- function(data, valid_data = NULL,
                       lrnr_stack, z_names, w_names) {
  #  construct task for propensity score fit
  m_task <- sl3::sl3_Task$new(
    data = data,
    covariates = c("A", z_names, w_names),
    outcome = "Y"
  )

  # fit and predict
  m_fit_stack <- lrnr_stack$train(m_task)

  # use full data for counterfactual prediction if no validation data provided
  if (is.null(valid_data)) {
    # copy full data
    data_A1 <- copy(data)
    data_A0 <- copy(data)
  } else {
    # copy only validation data
    data_A1 <- copy(valid_data)
    data_A0 <- copy(valid_data)
  }

  # copy data and set intervention A = 1
  data_A1[, A := rep(1, .N)]
  m_task_A1 <- sl3::sl3_Task$new(
    data = data_A1,
    covariates = c("A", z_names, w_names),
    outcome = "Y"
  )
  m_pred_A1 <- m_fit_stack$predict(m_task_A1)

  # copy data and set intervention A = 0
  data_A0[, A := rep(0, .N)]
  m_task_A0 <- sl3::sl3_Task$new(
    data = data_A0,
    covariates = c("A", z_names, w_names),
    outcome = "Y"
  )
  m_pred_A0 <- m_fit_stack$predict(m_task_A0)

  # output
  out <- list(
    m_pred = data.table::data.table(cbind(
      m_pred_A1 = m_pred_A1,
      m_pred_A0 = m_pred_A0
    )),
    m_fit_sl = m_fit_stack
  )
  return(out)
}

################################################################################

#' Fit intervention-specific exponential tilt nuisance parameter
#'
#' @param data A \code{data.table} containing the observed data, with columns
#'  in the order specified by the NPSEM (Y, Z, A, W), with column names set
#'  appropriately based on the original input data. Such a structure is merely
#'  a convenience utility to passing data around to the various core estimation
#'  routines and is automatically generated as part of a call to the user-facing
#'  wrapper function \code{medshift}.
#' @param lrnr_stack A \code{Stack} object, or other learner class (inheriting
#'  from \code{Lrnr_base}), containing a single or set of instantiated learners
#'  from the \code{sl3} package, to be used in fitting a cleverly parameterized
#'  propensity score that includes the mediators, i.e., e = P(A | Z, W).
#' @param m_output Object containing results from fitting the outcome
#'  regression, as produced by a call to \code{fit_m_mech}.
#' @param w_names A \code{character} vector of the names of the columns that
#'  correspond to baseline covariates (W). The input for this argument is
#'  automatically generated by a call to the wrapper function \code{medshift}.
#'
#' @importFrom data.table data.table as.data.table
#' @importFrom sl3 sl3_Task
#
fit_phi_mech <- function(data, lrnr_stack, m_output, w_names) {
  # difference-reduced dimension regression for phi
  m_pred_A1 <- m_output$m_pred$m_pred_A1
  m_pred_A0 <- m_output$m_pred$m_pred_A0
  m_pred_diff <- m_pred_A1 - m_pred_A0

  # construct data structure for use with task objects
  phi_data <- data.table::data.table(m_diff = m_pred_diff, data[, ..w_names])
  phi_task <- sl3::sl3_Task$new(
    data = phi_data,
    covariates = w_names,
    outcome = "m_diff",
    outcome_type = "continuous"
  )

  # fit stack of learners and predict on the same data set
  phi_fit <- lrnr_stack$train(phi_task)
  phi_est <- phi_fit$predict()
  return(phi_est)
}
