utils::globalVariables(c(".N"))

#' Fit outcome regression
#'
#' @param data A \code{data.table} containing the observed data, with columns
#'  in the order specified by the NPSEM (Y, Z, A, W), with column names set
#'  appropriately based on the original input data. Such a structure is merely
#'  a convenience utility to passing data around to the various core estimation
#'  routines and is automatically generated as part of a call to the user-facing
#'  wrapper function \code{medshift}.
#' @param valid_data A holdout data set, with columns exactly matching those
#'  appearing in the preceding argument \code{data}, to be used for estimation
#'  via cross-fitting. Optional, defaulting to \code{NULL}.
#' @param lrnr_stack A \code{Stack} object, or other learner class (inheriting
#'  from \code{Lrnr_base}), containing a single or set of instantiated learners
#'  from the \code{sl3} package, to be used in fitting the outcome regression,
#'  i.e., m(A, Z, W).
#' @param z_names A \code{character} vector of the names of the columns that
#'  correspond to mediators (Z). The input for this argument is automatically
#'  generated by a call to the wrapper function \code{medshift}.
#' @param w_names A \code{character} vector of the names of the columns that
#'  correspond to baseline covariates (W). The input for this argument is
#'  automatically generated by a call to the wrapper function \code{medshift}.
#'
#' @importFrom data.table as.data.table
#' @importFrom sl3 sl3_Task
#
fit_m_mech <- function(data, valid_data = NULL,
                       lrnr_stack, z_names, w_names) {
  #  construct task for propensity score fit
  m_task <- sl3::sl3_Task$new(
    data = data,
    covariates = c("A", z_names, w_names),
    outcome = "Y"
  )

  # fit and predict
  m_fit_stack <- lrnr_stack$train(m_task)

  # use full data for counterfactual prediction if no validation data provided
  if (is.null(valid_data)) {
    # copy full data
    data_A1 <- copy(data)
    data_A0 <- copy(data)
  } else {
    # copy only validation data
    data_A1 <- copy(valid_data)
    data_A0 <- copy(valid_data)
  }

  # copy data and set intervention A = 1
  data_A1[, A := rep(1, .N)]
  m_task_A1 <- sl3::sl3_Task$new(
    data = data_A1,
    covariates = c("A", z_names, w_names),
    outcome = "Y"
  )
  m_pred_A1 <- m_fit_stack$predict(m_task_A1)

  # copy data and set intervention A = 0
  data_A0[, A := rep(0, .N)]
  m_task_A0 <- sl3::sl3_Task$new(
    data = data_A0,
    covariates = c("A", z_names, w_names),
    outcome = "Y"
  )
  m_pred_A0 <- m_fit_stack$predict(m_task_A0)

  # output
  out <- list(
    m_pred = data.table::data.table(cbind(
      m_pred_A1 = m_pred_A1,
      m_pred_A0 = m_pred_A0
    )),
    m_fit_sl = m_fit_stack
  )
  return(out)
}
