utils::globalVariables(c(".N"))

#' Fit clever propensity score regression for mediators
#'
#' @param data A \code{data.table} containing the observed data, with columns
#'  in the order specified by the NPSEM (Y, Z, A, W), with column names set
#'  appropriately based on the original input data. Such a structure is merely
#'  a convenience utility to passing data around to the various core estimation
#'  routines and is automatically generated as part of a call to the user-facing
#'  wrapper function \code{medshift}.
#' @param valid_data A holdout data set, with columns exactly matching those
#'  appearing in the preceding argument \code{data}, to be used for estimation
#'  via cross-fitting. Optional, defaulting to \code{NULL}.
#' @param lrnr_stack A \code{Stack} object, or other learner class (inheriting
#'  from \code{Lrnr_base}), containing a single or set of instantiated learners
#'  from the \code{sl3} package, to be used in fitting a cleverly parameterized
#'  propensity score that includes the mediators, i.e., e = P(A | Z, W).
#' @param z_names A \code{character} vector of the names of the columns that
#'  correspond to mediators (Z). The input for this argument is automatically
#'  generated by a call to the wrapper function \code{medshift}.
#' @param w_names A \code{character} vector of the names of the columns that
#'  correspond to baseline covariates (W). The input for this argument is
#'  automatically generated by a call to the wrapper function \code{medshift}.
#'
#' @importFrom data.table as.data.table
#' @importFrom sl3 sl3_Task
#
fit_e_mech <- function(data, valid_data = NULL,
                       lrnr_stack, z_names, w_names) {
  # construct task for nuisance parameter fit
  e_task <- sl3::sl3_Task$new(
    data = data,
    covariates = c(z_names, w_names),
    outcome = "A"
  )

  # fit and predict
  e_fit_stack <- lrnr_stack$train(e_task)

  # use full data for counterfactual prediction if no validation data provided
  if (is.null(valid_data)) {
    # copy full data
    data_A1 <- data.table::copy(data)
  } else {
    # copy only validation data
    data_A1 <- data.table::copy(valid_data)
  }

  # set intervention A = 1 in validation data or full data
  data_A1[, A := rep(1, .N)]
  e_task_A1 <- sl3_Task$new(
    data = data_A1,
    covariates = c(z_names, w_names),
    outcome = "A"
  )

  # predict from trained model on counterfactual data
  e_pred_A1 <- e_fit_stack$predict(e_task_A1)

  # get values of nuisance parameter E for A = 0 by symmetry with A = 1 case
  e_pred_A0 <- 1 - e_pred_A1 

  # bounding to numerical precision
  e_pred_A1 <- bound_precision(e_pred_A1)
  e_pred_A0 <- bound_precision(e_pred_A0)

  # bounding for potential positivity issues
  e_pred_A1 <- bound_propensity(e_pred_A1)
  e_pred_A0 <- bound_propensity(e_pred_A0)

  # output
  out <- list(
    e_est = data.table::data.table(cbind(e_pred_A1 = e_pred_A1,
                                         e_pred_A0 = e_pred_A0)),
    e_fit = e_fit_stack
  )
  return(out)
}
