#' Incremental Propensity Score Intervention
#'
#' Compute the exponential tilt shift, which corresponds to an incremental
#' propensity score intervention on gn := Pr(A = 1 | W).
#'
#' @param gn_est A \code{numeric} vector of the estimated propensity score, the
#'  probability of receiving treatment A given baseline covariates W.
#' @param delta A \code{numeric} scalar giving the degree by which the odds of
#'  receiving treatment are shifted in this type of intervention.
#'
#' @export
ipsi_shift <- function(gn_est, delta) {
  gn_est_shifted <- (delta * gn_est) / (delta * gn_est + (1 - gn_est))
  return(gn_est_shifted)
}

#' Additive Modified Treatment Policy
#'
#' Compute the shift intervention: d(A,W) = A + delta.
#'
#' @param A The \code{numeric} vector of natural observed values of treatment.
#' @param W The \code{numeric} vector, \code{matrix}, \code{data.frame} or
#'  similar object giving the values of the baseline covariates.
#' @param delta The \code{numeric} scalar giving the degree by which naturally
#'  observed values of the intervention \code{A} ought to be shifted.
#'
#' @export
mtp_shift <- function(A, W = NULL, delta) {
  if (is.null(W)) {
    # just assume unbounded support for A|W for now...
    A_shifted <- A + delta
  } else {
    # NOTE: input for W should be get(w_names) when called from an environment
    #       generated by data.table
    # assume unbounded support of A|W for now...
    A_shifted <- A + delta
  }
  return(A_shifted)
}

#' Inverse Additive Modified Treatment Policy
#'
#' Compute the inverse shift intervention: d(A,W) = A - delta, a term appearing
#' in the definition of the shifted intervention quantity for this shift type.
#'
#' @param A The \code{numeric} vector of natural observed values of treatment.
#' @param W The \code{numeric} vector, \code{matrix}, \code{data.frame} or
#'  similar object giving the values of the baseline covariates.
#' @param delta The \code{numeric} scalar giving the degree by which naturally
#'  observed values of the intervention \code{A} ought to be shifted.
#'
#' @export
mtp_shift_inv <- function(A, W = NULL, delta) {
  if (is.null(W)) {
    # just assume unbounded support for A|W for now...
    A_shifted <- A - delta
  } else {
    # NOTE: input for W should be get(w_names) when called from an environment
    #       generated by data.table
    # assume unbounded support of A|W for now...
    A_shifted <- A - delta
  }
  return(A_shifted)
}
